In [1]:
import numpy as np

In [12]:
data = np.array([[1,2], [3,4]])
constant_arr = np.array([[5,5], [5,5]])
data + constant_arr

array([[6, 7],
       [8, 9]])

In [13]:
data = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
constant_arr = np.array([[[5,5], [5,5]], [[5,5], [5,5]]])
data + constant_arr

array([[[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]])

In [14]:
constant_arr = np.full((data.shape), 5)
data + constant_arr

array([[[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]])

In [15]:
data + 5

array([[[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]])

In [20]:
new_arr = np.ones(3, dtype=int)
data + new_arr

ValueError: operands could not be broadcast together with shapes (2,2,2) (3,) 

In [21]:
a = np.array([[2,4], [6,8]])
b = np.array([1,3])
a + b

array([[ 3,  7],
       [ 7, 11]])

In [22]:
a = np.array([[2,4], [6,8]])
b = np.array([[1], [3]])
a + b

array([[ 3,  5],
       [ 9, 11]])

In [23]:
a = np.array([[2,4], [6,8]])
b = np.array([[1,3,5], [2,4,6]])
a + b

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 